fix: check that required arguments are set
Fixes MRGFY-3942

Change-Id: I3394ee095ded814fce4ad872a1c1d134d3846a83

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -36,6 +36,17 @@ runs:
       run: |
         set -x
 
+        # Check if FILES and MERGIFY_CI_ISSUES_TOKEN are set and not empty
+        if [ -z "$FILES" ]; then
+          echo "::error:: report_paths is not set or is empty"
+          exit 1
+        fi
+
+        if [ -z "$MERGIFY_CI_ISSUES_TOKEN" ]; then
+          echo "::error:: token is not set or is empty"
+          exit 1
+        fi
+
         # TODO(sileht): support multiple files
         curl -X POST \
           -H "Authorization: bearer ${MERGIFY_CI_ISSUES_TOKEN}" \
